trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleDebug'
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleDebugAndroidTest'

- task: ShellScript@2
  inputs:
    scriptPath: | 
       "appcenter test run espresso --app "alexe_ytiurin/EspressoGuide" --devices 9c9a9823 --app-path "app/build/outputs/apk/debug/app-debug.apk" --test-series "master" --locale "en_US" --build-dir "app/build/outputs/apk/androidTest/debug" --token a0357d76e812fed47733821dc7113488dc51e0a9"