name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macOS-10.15

    steps:
      - name: Execute Instrumentation Tests (gradlew connectedCheck - api 23)
        
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 23
          target: default
          arch: x86
          profile: Nexus 6
          script: ./gradlew connectedCheck --stacktrace
